Добавление скрипта для управления проектными ролями через regex
POSIdev-community/ptai-scripts pull request #1
Opened 2024-02-27 09:05 UTC by AipNooBest

2024-02-27 11:55 UTC, vldF commented on regex-role-changer/main.py
> +    sys.exit(0)
Я бы тут сделал вывод сообщения о том, что операция прервана. А то может показаться, что изменения применились. Мало ли кто-то нечаянно введет у (русская буква у)

```suggestion
    print("Отмена операции, изменения не будут применены")
    sys.exit(0)
```

2024-02-27 11:56 UTC, vldF commented on regex-role-changer/main.py
> +        print(f"ERR: Ошибка при изменении проектов пользователя {username}. Сервер вернул код {req.status_code}")
Давайте, раз тут нет обработки других кодов ошибок, сделаем тут вывод текста ответа? Это может существенно упростить понимание ошибки

2024-02-27 12:01 UTC, vldF commented on regex-role-changer/main.py
> +        if req.status_code == 400 and req.json()['errorCode'] == 'CANNOT_ASSIGN_PROJECT_ROLE_TO_ADMINISTRATOR':
Кажется, тут будет `KeyError` в случае, если при ответе с четырёхсоткой сервер вернёт какую-то другую модельку. Может, обработаете эту ситуацию?

2024-02-27 12:05 UTC, vldF commented on regex-role-changer/requirements.txt
> +pwinput==1.0.3
А зачем тут эта зависимость? Не вижу её явного использования (как и некоторых других). Они точно все необходимы?

2024-02-27 12:06 UTC, vldF requested changes
Спасибо за вклад, внесите, пожалуйста, правки

2024-02-27 14:13 UTC, AipNooBest commented on regex-role-changer/requirements.txt
> +pwinput==1.0.3
И правда, часть зависимостей попала из-за их использования в ранних версиях скрипта. Если вопрос про pwinput - он используется для запроса пароля в [методе get_bearer_token() в файле auth.py](https://github.com/Swordfish-Security/ptai-scripts/blob/78ad91e6f30d048a74087c2ec0feb66b2de7b230/regex-role-changer/auth.py#L32-L33). certifi, charset-normalizer и idna - зависимости requests

2024-02-27 14:15 UTC, AipNooBest commented
Правки внесены, проверьте, пожалуйста

2024-02-27 15:05 UTC, vldF commented on regex-role-changer/requirements.txt
> +pwinput==1.0.3
Спасибо, с pwinput понял

Можете актуализировать тогда список в общем?

2024-02-27 15:05 UTC, vldF commented on regex-role-changer/requirements.txt
> +pwinput==1.0.3
А, кажется, уже исправили

2024-02-27 15:07 UTC, vldF approved these changes
Спасибо за вклад в наше сообщество!

2024-02-27 15:07 UTC, merged

2024-03-11 13:18 UTC, sergiomarotco commented on regex-role-changer/README.md
`Находясь в директории проекта написать в консоли `
Почему бы сразу не использовать полные пути? Чтобы не находиться в директории